server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 4096
  undertow:
    threads:
      worker: 64
      io: 8  
    options:
      idle-timeout: 15000  
      max-connections: 3000

spring:
  redis:
    host: localhost
    port: 6379
    password: "" # Adicione a senha se necessário
    database: 0   