server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 4096
  undertow:
    threads:
      worker: 64
      io: 8  
    options:
      idle-timeout: 30000  
      max-connections: 2000  